### ISSUE TITLE
KeyError: '0_Parade_marchingband_1_465'

### ISSUE THREAD

**Issue by xauat-liushipeng** [wondervictor/WiderFace-Evaluation#12]
why do it have this error?   I have run **python setup.py build_ext --inplace**
and **python3 evaluation.py -p results/ -g ground_truth/**

details:
Reading Predictions : 100%|█████████████████████| 61/61 [00:00<00:00, 93.52it/s]
Processing easy:   0%|                                   | 0/61 [00:00<?, ?it/s]Traceback (most recent call last):
  File "evaluation.py", line 280, in <module>
    evaluation(args.pred, args.gt)
  File "evaluation.py", line 242, in evaluation
    pred_info = pred_list[str(img_list[j][0][0])]
KeyError: '0_Parade_marchingband_1_465'
Processing easy:   0%|                                   | 0/61 [00:00<?, ?it/s]

**Comment by xauat-liushipeng** [comment]
sorry, i have solve the problem. But how can i get the PR curve?

**Comment by kingjames1155** [comment]
can you tell me How did you solve this problem?

**Comment by kingjames1155** [comment]
> sorry, i have solve the problem. But how can i get the PR curve?

excuse me ,can you tell me How did you solve this problem?

**Comment by viljamirom** [comment]
> > sorry, i have solve the problem. But how can i get the PR curve?
> 
> excuse me ,can you tell me How did you solve this problem?

Make sure that you are using the validation data set for producing your predictions. (since the ground truths are for validation) Other option might be that for some reason you don't have the matching file in your predictions.

**Comment by NguyenKhacTuanAnh** [comment]
why do it have this error? I have run python setup.py build_ext --inplace
and python3 evaluation.py -p results/ -g ground_truth/

details:
0it [00:00, ?it/s]
Processing easy:   0%|                                                                    | 0/61 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "evaluation.py", line 287, in <module>
    evaluation(args.pred, args.gt)
  File "evaluation.py", line 236, in evaluation
    pred_list = pred[event_name]
KeyError: '0--Parade'

**Comment by NguyenKhacTuanAnh** [comment]
> sorry, i have solve the problem. But how can i get the PR curve?



> why do it have this error? I have run **python setup.py build_ext --inplace**
> and **python3 evaluation.py -p results/ -g ground_truth/**
> 
> details:
> Reading Predictions : 100%|█████████████████████| 61/61 [00:00<00:00, 93.52it/s]
> Processing easy: 0%| | 0/61 [00:00<?, ?it/s]Traceback (most recent call last):
> File "evaluation.py", line 280, in
> evaluation(args.pred, args.gt)
> File "evaluation.py", line 242, in evaluation
> pred_info = pred_list[str(img_list[j][0][0])]
> KeyError: '0_Parade_marchingband_1_465'
> Processing easy: 0%| | 0/61 [00:00<?, ?it/s]

Excuse me. How do you solve problem?
Thank you

**Comment by xauat-liushipeng** [comment]
> > sorry, i have solve the problem. But how can i get the PR curve?
> 
> > why do it have this error? I have run **python setup.py build_ext --inplace**
> > and **python3 evaluation.py -p results/ -g ground_truth/**
> > details:
> > Reading Predictions : 100%|█████████████████████| 61/61 [00:00<00:00, 93.52it/s]
> > Processing easy: 0%| | 0/61 [00:00<?, ?it/s]Traceback (most recent call last):
> > File "evaluation.py", line 280, in
> > evaluation(args.pred, args.gt)
> > File "evaluation.py", line 242, in evaluation
> > pred_info = pred_list[str(img_list[j][0][0])]
> > KeyError: '0_Parade_marchingband_1_465'
> > Processing easy: 0%| | 0/61 [00:00<?, ?it/s]
> 
> Excuse me. How do you solve problem?
> Thank you

I'm sorry forgot it. May be there is nothing in dir 'results'？

**Comment by NguyenKhacTuanAnh** [comment]
> > > sorry, i have solve the problem. But how can i get the PR curve?
> > 
> > 
> > > why do it have this error? I have run **python setup.py build_ext --inplace**
> > > and **python3 evaluation.py -p results/ -g ground_truth/**
> > > details:
> > > Reading Predictions : 100%|█████████████████████| 61/61 [00:00<00:00, 93.52it/s]
> > > Processing easy: 0%| | 0/61 [00:00<?, ?it/s]Traceback (most recent call last):
> > > File "evaluation.py", line 280, in
> > > evaluation(args.pred, args.gt)
> > > File "evaluation.py", line 242, in evaluation
> > > pred_info = pred_list[str(img_list[j][0][0])]
> > > KeyError: '0_Parade_marchingband_1_465'
> > > Processing easy: 0%| | 0/61 [00:00<?, ?it/s]
> > 
> > 
> > Excuse me. How do you solve problem?
> > Thank you
> 
> I'm sorry forgot it. May be there is nothing in dir 'results'？
I modify dir 'result' as below image. Where am i wrong?
![Screenshot from 2021-06-11 11-07-55](https://user-images.githubusercontent.com/81618926/121629603-bd57e200-caa5-11eb-82f3-7dfd67af7bac.png)

**Comment by xauat-liushipeng** [comment]
> > > > sorry, i have solve the problem. But how can i get the PR curve?
> > > 
> > > 
> > > > why do it have this error? I have run **python setup.py build_ext --inplace**
> > > > and **python3 evaluation.py -p results/ -g ground_truth/**
> > > > details:
> > > > Reading Predictions : 100%|█████████████████████| 61/61 [00:00<00:00, 93.52it/s]
> > > > Processing easy: 0%| | 0/61 [00:00<?, ?it/s]Traceback (most recent call last):
> > > > File "evaluation.py", line 280, in
> > > > evaluation(args.pred, args.gt)
> > > > File "evaluation.py", line 242, in evaluation
> > > > pred_info = pred_list[str(img_list[j][0][0])]
> > > > KeyError: '0_Parade_marchingband_1_465'
> > > > Processing easy: 0%| | 0/61 [00:00<?, ?it/s]
> > > 
> > > 
> > > Excuse me. How do you solve problem?
> > > Thank you
> > 
> > 
> > I'm sorry forgot it. May be there is nothing in dir 'results'？
> > I modify dir 'result' as below image. Where am i wrong?
> > ![Screenshot from 2021-06-11 11-07-55](https://user-images.githubusercontent.com/81618926/121629603-bd57e200-caa5-11eb-82f3-7dfd67af7bac.png)

I did forget. You can try another method.Just after you get your test results, you can try the official MATLAB Toolbox

**Comment by huashunfu** [comment]
the inconsistence between data and ground true may bring this error
